### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by RanaInside** [DarrenTsung/DTValidator#1]
Hi Darren,

this is really really good; I've been annoyed with unity's lack of information on missing outlets and this solves all those issues; Now there are couple of things that would just make this perfect.

1) Instead of IgnoredNamespace have a ProcessOnlyNamespace; way too many developers in Unity writes their code without namespace - even things like SteamVR; So it would be more useful if I can get this to validate only my namespace.

2) Option to scan scenes only in build and not saved scenes - as some assets come with demo scenes that at times we leave within project; no point of validator checking them.

Thanks again.
Rana

**Comment by DarrenTsung** [comment]
Hi Rana,

Thanks for the kind words, I'm glad this helps you!

1. Yeah I see a lot of code with namespaces - adding a ProcessOnlyNamespace will be easy, but I'll have to figure out where to switch from blacklist to whitelist.. maybe if any ProcessOnlyNamespace assets are found in the project?

2. Yeah I can add another option / unit test and you can just disable the ones you don't need :).

**Comment by DarrenTsung** [comment]
If you get the latest from master you should have all of the changes :).

1. Added a ValidatorWhitelistedNamespace - if any are found in the project it will whitelist instead of blacklist.

2. Merged in @deltaohio's pull-request here: https://github.com/DarrenTsung/DTValidator/pull/2. Added in an option for only validating the build scenes + a unit test that you have to enable in the default included unit tests.
