### ISSUE TITLE
Ignore Class

### ISSUE THREAD

**Issue by bfercher** [DarrenTsung/DTValidator#8]
Thank you for the great work. Is there a possibility to ignore a class? I have the use-case that derivations from 3rd party classes also bring errors and then its not possible to make exposed variables (from the parent-class) optional. How do you handle such a case? The only solution which comes to my mind is to open a new namespace for those derived classes and solve it with IgnoreNamespace, but thats actually not what I want to do.

**Comment by DarrenTsung** [comment]
Hi, thanks! There doesn't exist a solution for that case currently. 

It shouldn't be that hard to add though, and you should be able to validate your derived class outlets while ignoring the base class exposed variables. 

This is very similar to the use-case for classes derived from Unity classes, where we ignore variables declared in the Unity assembly (out of our control) from being validated.

I don't currently work on this project / with Unity anymore, but if you'd like to open a PR I believe it would be relatively simple.

1. Fork / switch to `develop` branch
2. Create a ScriptableObject named something like `ValidatorBlacklistedClass` (based off of [ValidatorWhitelistedNamespace](https://github.com/DarrenTsung/DTValidator/blob/master/Validation/ValidatorWhitelistedNamespace.cs))
3. Create a static `Provider` class with loading the assets as a default (based off of [ValidatorWhitelistedNamespaceProvider](https://github.com/DarrenTsung/DTValidator/blob/master/Validation/Editor/ValidatorWhitelistedNamespacesProvider/ValidatorWhitelistedNamespaceProvider.cs))
4. Add a check that the field's `DeclaringType`'s name does not match any blacklisted class [here](https://github.com/DarrenTsung/DTValidator/blob/master/Validation/Editor/Validator.cs#L161).
5. Add a test that blacklisted classes as base classes don't create validation errors as expected like [here](https://github.com/DarrenTsung/DTValidator/blob/develop/Tests/Editor/ValidatorIgnoredNamespaceTests.cs).

**Comment by MarleneMayr** [comment]
@DarrenTsung Hi,
I added this feature in my project. But I am not sure how I can correctly contribute to your tool. GitHub states that the master is 4 commits ahead of develop branch. And unfortunately I am not familiar with opening PRs to public repos. Could you give me some info on how to integrate my changes?

**Comment by DarrenTsung** [comment]
Hi @MarleneMayr, thanks for your interest in contributing to this repo!

You can ignore the `develop` branch, it was an attempt to keep the `master` branch clonable into someone's repository without tests, but really we should be using some sort of binary / package release system specified in #9. 

I have since added the tests back to `master` and deleted the `develop` branch.

To contribute the feature you've built to the project, I would suggest doing:
1. Create a personal fork of the project based off the current state
2. Clone that fork onto a local copy on your computer
3. Create a branch in your fork called `validator-blacklisted-class` off `master`
4. Copy over only the code for this feature you've developed into your local copy
5. Test that your feature works locally as expected and write tests based off of `ValidatorIgnoredNamespaceTests.cs`
6. Commit / push your branch
7. Open a new pull-request for _this_ project, merging `your_fork/validator-blacklisted-class` into `DTValidator/master`
8. I will leave feedback / help test it out
9. Once feedback is good, I'll approve and merge into the project

I hope this helps! I think there are many nuances that I may have not covered, but you can look into other resources on this topic like: https://github.com/MarcDiethelm/contributing/blob/master/README.md.

**Comment by MarleneMayr** [comment]
Thanks for your quick answer and detailed explanation!
I did exactly as you said and hope it helps to improve the tool.

**Comment by DarrenTsung** [comment]
Fixed with #11
